services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web
      POSTGRES_DB: dishes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "9999:5432"
volumes:
  pgdata:


